
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pagerank-test_development
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pagerank-test_production
  pool: 5
  username: root
  password: 
  host: localhost
