
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pagerank-test_development
  pool: 5
  username: root
  password:
  host: localhost
  
production:
  adapter: mysql2
  encoding: utf8
  database: pagerank_production
  pool: 5
  host: 10.0.1.101
  username: bingo
  password: db
